import {
  CampaignBrief,
  ExecutionPipelineStage,
  ExecutionRisk,
  ExecutionTask,
  KPIBundle,
  MonitoringAlert,
  MonitoringBreakdown,
  MonitoringFunnelStep,
  MonitoringKPI,
  MonitoringSavedView,
  MonitoringSeries,
  Opportunity,
  SegmentDefinition,
  SegmentRuleCondition,
  SegmentRuleGroup,
  SegmentSampleProfile,
  SegmentVersion,
} from "./types";

export const macroZones = [
  "San Juan Metro",
  "Bayamón",
  "Carolina",
  "Caguas",
  "Ponce",
  "Mayagüez",
  "Arecibo",
  "Fajardo/Río Grande",
];

const deriveIntensity = (primary: string, zone: string, base: number) => {
  const primaryIdx = macroZones.indexOf(primary);
  const zoneIdx = macroZones.indexOf(zone);
  const falloff = Math.min(Math.abs(primaryIdx - zoneIdx) * 0.12, 0.48);
  return Number(Math.max(0.18, base - falloff).toFixed(2));
};

const mkMicroGeo = (primary: string, base: number) =>
  macroZones.map((zone) => ({ zone, intensity: deriveIntensity(primary, zone, base) }));

const mkLineage = (refreshed: string) => [
  { source: "Subscriber telemetry mart", refreshed },
  { source: "Consent lakehouse", refreshed },
  { source: "Channel readiness warehouse", refreshed },
];

export const opportunities: Opportunity[] = [
  {
    id: "opp-001",
    title: "Fiber upgrade in San Juan Metro",
    objective: "grow",
    product: "Fiber",
    zone: "San Juan Metro",
    subscriberCount: 3200,
    estimatedValue: 42000,
    confidence: 0.68,
    planType: "postpaid",
    subscriberType: "consumer",
    language: "es",
    outageProne: false,
    affordabilityRisk: true,
    whyNow: "Promo expirations coincide with Claro price increases across Condado and Miramar blocks.",
    trend: { direction: "up", change: 6.1, period: "WoW" },
    reachability: {
      email: true,
      sms: true,
      whatsapp: true,
      retail: false,
      callCenter: true,
      eligiblePct: 72,
    },
    previewAudience: 4800,
    signals: ["promo change", "affordability program lapse"],
    summary:
      "Postpaid bilingual households trending toward promo expiry and actively searching bundle incentives.",
    drivers: ["price sensitivity", "bundle eligibility"],
    assumptions: [
      "Liberty Loop bundling incentives resonate with converged households.",
      "Residents expect proactive outreach in Spanish within 48 hours of promo change.",
    ],
    microGeo: mkMicroGeo("San Juan Metro", 0.82),
    benchmarks: [
      { competitor: "Claro PR", offer: "300Mbps", price: 55 },
      { competitor: "Liberty PR", offer: "500Mbps", price: 60 },
    ],
    lineage: mkLineage("2024-04-22T08:30:00Z"),
    recommendedAttributes: ["language", "planType", "zone", "arpuBand", "bundleEligible"],
  },
  {
    id: "opp-002",
    title: "Storm recovery mobile relief",
    objective: "retain",
    product: "Mobile",
    zone: "Mayagüez",
    subscriberCount: 2800,
    estimatedValue: 21000,
    confidence: 0.62,
    planType: "prepaid",
    subscriberType: "consumer",
    language: "es",
    outageProne: true,
    affordabilityRisk: false,
    whyNow: "Network disruptions from the last storm created escalations and top-up hesitancy.",
    trend: { direction: "down", change: -4.3, period: "MoM" },
    reachability: {
      email: false,
      sms: true,
      whatsapp: true,
      retail: true,
      callCenter: true,
      eligiblePct: 58,
    },
    previewAudience: 3100,
    signals: ["storm recovery", "network event"],
    summary: "Prepaid Spanish-first users impacted by storm; highly responsive to WhatsApp outreach.",
    drivers: ["outage impact"],
    assumptions: [
      "Field readiness teams can coordinate service credits within 72 hours.",
      "WhatsApp outreach remains the most trusted channel post-storm.",
    ],
    microGeo: mkMicroGeo("Mayagüez", 0.78),
    benchmarks: [{ competitor: "T-Mobile PR", offer: "Hurricane relief bonus", price: 0 }],
    lineage: mkLineage("2024-04-21T12:00:00Z"),
    recommendedAttributes: ["language", "prepaid", "zone", "consentWhatsApp", "consentSMS"],
  },
  {
    id: "opp-003",
    title: "Liberty Loop bundle expansion",
    objective: "acquire",
    product: "Bundle",
    zone: "Bayamón",
    subscriberCount: 1900,
    estimatedValue: 38000,
    confidence: 0.7,
    planType: "bundle",
    subscriberType: "small-business",
    language: "en",
    outageProne: false,
    affordabilityRisk: false,
    whyNow: "Retailers planning omnichannel rollouts need converged connectivity and voice.",
    trend: { direction: "up", change: 8.2, period: "WoW" },
    reachability: {
      email: true,
      sms: true,
      whatsapp: false,
      retail: true,
      callCenter: true,
      eligiblePct: 65,
    },
    previewAudience: 2100,
    signals: ["promo change", "bundle interest"],
    summary: "Multi-location retailers considering Liberty Loop for unified connectivity and voice.",
    drivers: ["bundle eligibility"],
    assumptions: [
      "Decision makers prefer English-first proposals with ROI breakdowns.",
      "Loop bundles outperform AeroNet on resiliency commitments.",
    ],
    microGeo: mkMicroGeo("Bayamón", 0.74),
    benchmarks: [{ competitor: "AeroNet", offer: "Business duo play", price: 85 }],
    lineage: mkLineage("2024-04-20T15:45:00Z"),
    recommendedAttributes: ["bundleEligible", "language", "zone", "planType"],
  },
  {
    id: "opp-004",
    title: "Ponce FWA surge",
    objective: "acquire",
    product: "FWA",
    zone: "Ponce",
    subscriberCount: 2500,
    estimatedValue: 24000,
    confidence: 0.56,
    planType: "postpaid",
    subscriberType: "consumer",
    language: "es",
    outageProne: true,
    affordabilityRisk: false,
    whyNow: "Storm-prone households need redundant connectivity alongside DSL.",
    trend: { direction: "up", change: 5.4, period: "MoM" },
    reachability: {
      email: true,
      sms: true,
      whatsapp: true,
      retail: false,
      callCenter: false,
      eligiblePct: 49,
    },
    previewAudience: 2700,
    signals: ["network event", "bundle interest"],
    summary: "Storm-prone households needing redundant connectivity; open to FWA as backup.",
    drivers: ["outage impact", "bundle eligibility"],
    assumptions: [
      "Households accept proactive SMS if recovery SLA is explicit.",
      "Bundled FWA + mobile single-line priced under $65 performs best.",
    ],
    microGeo: mkMicroGeo("Ponce", 0.71),
    benchmarks: [{ competitor: "Claro PR", offer: "Fixed Wireless", price: 50 }],
    lineage: mkLineage("2024-04-19T09:20:00Z"),
    recommendedAttributes: ["zone", "planType", "consentSMS", "bundleEligible"],
  },
  {
    id: "opp-005",
    title: "Enterprise fiber anchor",
    objective: "grow",
    product: "Fiber",
    zone: "San Juan Metro",
    subscriberCount: 1100,
    estimatedValue: 60000,
    confidence: 0.64,
    planType: "postpaid",
    subscriberType: "small-business",
    language: "en",
    outageProne: false,
    affordabilityRisk: false,
    whyNow: "Professional services clusters scaling hybrid workrooms across Hato Rey.",
    trend: { direction: "up", change: 3.3, period: "WoW" },
    reachability: {
      email: true,
      sms: false,
      whatsapp: false,
      retail: false,
      callCenter: true,
      eligiblePct: 61,
    },
    previewAudience: 1500,
    signals: ["network event"],
    summary: "Professional services cluster seeking symmetrical fiber to support hybrid work.",
    drivers: ["bundle eligibility"],
    assumptions: [
      "Decision makers expect low-latency SLA commitments.",
      "Executive briefings should emphasise managed security bundles.",
    ],
    microGeo: mkMicroGeo("San Juan Metro", 0.69),
    benchmarks: [{ competitor: "Liberty PR", offer: "Dedicated fiber", price: 125 }],
    lineage: mkLineage("2024-04-18T11:05:00Z"),
    recommendedAttributes: ["planType", "zone", "deviceOS", "language"],
  },
  {
    id: "opp-006",
    title: "Carolina prepaid retention",
    objective: "retain",
    product: "Mobile",
    zone: "Carolina",
    subscriberCount: 3600,
    estimatedValue: 18000,
    confidence: 0.59,
    planType: "prepaid",
    subscriberType: "consumer",
    language: "es",
    outageProne: false,
    affordabilityRisk: true,
    whyNow: "Competitors pushing $25 unlimited offers driving churn signals in Isla Verde.",
    trend: { direction: "down", change: -3.8, period: "WoW" },
    reachability: {
      email: true,
      sms: true,
      whatsapp: true,
      retail: true,
      callCenter: true,
      eligiblePct: 66,
    },
    previewAudience: 3900,
    signals: ["churn spike", "promo change"],
    summary: "Prepaid cohorts with high WhatsApp consent showing churn intent.",
    drivers: ["price sensitivity"],
    assumptions: [
      "SMS loyalty streak mechanics can stabilise churn risk.",
      "Spanish-first copy needs price-comparison framing.",
    ],
    microGeo: mkMicroGeo("Carolina", 0.63),
    benchmarks: [{ competitor: "Claro PR", offer: "Unlimited Prepaid", price: 25 }],
    lineage: mkLineage("2024-04-17T10:10:00Z"),
    recommendedAttributes: ["language", "prepaid", "consentWhatsApp", "zone"],
  },
  {
    id: "opp-007",
    title: "Arecibo fiber retention",
    objective: "retain",
    product: "Fiber",
    zone: "Arecibo",
    subscriberCount: 2200,
    estimatedValue: 26000,
    confidence: 0.61,
    planType: "postpaid",
    subscriberType: "consumer",
    language: "es",
    outageProne: true,
    affordabilityRisk: false,
    whyNow: "Heavy rains strain aerial fiber runs causing support surges.",
    trend: { direction: "flat", change: 0, period: "WoW" },
    reachability: {
      email: true,
      sms: true,
      whatsapp: false,
      retail: false,
      callCenter: true,
      eligiblePct: 57,
    },
    previewAudience: 2500,
    signals: ["network event"],
    summary: "Fiber households needing proactive retention credits during rainy season.",
    drivers: ["outage impact"],
    assumptions: [
      "Proactive credit communication reduces inbound call volume by 14%.",
      "SMS with localised weather copy converts best.",
    ],
    microGeo: mkMicroGeo("Arecibo", 0.6),
    benchmarks: [{ competitor: "Claro PR", offer: "Fiber 200", price: 50 }],
    lineage: mkLineage("2024-04-16T16:45:00Z"),
    recommendedAttributes: ["zone", "planType", "consentSMS"],
  },
  {
    id: "opp-008",
    title: "Fajardo roaming upsell",
    objective: "grow",
    product: "Mobile",
    zone: "Fajardo/Río Grande",
    subscriberCount: 1400,
    estimatedValue: 15000,
    confidence: 0.52,
    planType: "postpaid",
    subscriberType: "consumer",
    language: "en",
    outageProne: false,
    affordabilityRisk: false,
    whyNow: "Tourism recovery brings demand for North America roaming packs.",
    trend: { direction: "up", change: 2.4, period: "WoW" },
    reachability: {
      email: true,
      sms: true,
      whatsapp: false,
      retail: true,
      callCenter: true,
      eligiblePct: 54,
    },
    previewAudience: 1600,
    signals: ["promo change"],
    summary: "Travel-heavy postpaid lines showing high roaming pack attach propensity.",
    drivers: ["bundle eligibility"],
    assumptions: [
      "English-first copy referencing airport flows resonates best.",
      "Roaming pack auto-renew incentives lift ARPU by $11.",
    ],
    microGeo: mkMicroGeo("Fajardo/Río Grande", 0.58),
    benchmarks: [{ competitor: "T-Mobile PR", offer: "Magenta Travel", price: 65 }],
    lineage: mkLineage("2024-04-15T13:15:00Z"),
    recommendedAttributes: ["language", "planType", "zone", "arpuBand"],
  },
  {
    id: "opp-009",
    title: "Caguas family bundle expansion",
    objective: "acquire",
    product: "Bundle",
    zone: "Caguas",
    subscriberCount: 2600,
    estimatedValue: 33000,
    confidence: 0.66,
    planType: "bundle",
    subscriberType: "consumer",
    language: "es",
    outageProne: false,
    affordabilityRisk: true,
    whyNow: "Families consolidating streaming subscriptions ahead of summer.",
    trend: { direction: "up", change: 7.1, period: "MoM" },
    reachability: {
      email: true,
      sms: true,
      whatsapp: true,
      retail: true,
      callCenter: true,
      eligiblePct: 69,
    },
    previewAudience: 3000,
    signals: ["promo change", "bundle interest"],
    summary: "Spanish-first families adding Liberty Loop to existing mobile lines.",
    drivers: ["bundle eligibility", "price sensitivity"],
    assumptions: [
      "Installment discounts with streaming credits close deals.",
      "Door-to-door retail can cover remaining holdouts.",
    ],
    microGeo: mkMicroGeo("Caguas", 0.73),
    benchmarks: [
      { competitor: "Claro PR", offer: "Triple Play", price: 75 },
      { competitor: "AeroNet", offer: "Streaming bundle", price: 78 },
    ],
    lineage: mkLineage("2024-04-14T10:00:00Z"),
    recommendedAttributes: ["bundleEligible", "language", "zone", "consentWhatsApp"],
  },
];

const mkGroup = (id: string, children: (SegmentRuleCondition | SegmentRuleGroup)[], combinator: "AND" | "OR" = "AND"): SegmentRuleGroup => ({
  id,
  combinator,
  children,
});

const mkVersion = (
  id: string,
  summary: string,
  timestamp: string,
  rules: SegmentRuleGroup,
  size: number,
): SegmentVersion => ({
  id,
  summary,
  timestamp,
  rules,
  metrics: {
    size,
    trend: 3.2,
    freshness: timestamp,
    reach: {
      email: Math.round(size * 0.78),
      sms: Math.round(size * 0.74),
      whatsapp: Math.round(size * 0.62),
      retail: Math.round(size * 0.39),
      callCenter: Math.round(size * 0.55),
      paidSocial: Math.round(size * 0.88),
      display: Math.round(size * 1.02),
    },
    warnings: [],
    impact: {
      propensity: 0.18,
      conversions: Math.round(size * 0.18),
      revenue: Math.round(size * 0.18 * 58),
      paybackDays: 38,
      cost: Math.round(size * 11),
      margin: Math.round(size * 0.18 * 58 - size * 11),
    },
  },
});

export const segmentDefinitions: SegmentDefinition[] = [
  {
    id: "seg-001",
    name: "Postpaid high-ARPU iOS loyalists",
    description: "English-first postpaid lines with high ARPU and iOS affinity across metro zones.",
    size: 18500,
    trend: 4.2,
    freshness: "2024-04-22T09:00:00Z",
    lastEdited: "2024-04-22T09:00:00Z",
    language: "en",
    rules: mkGroup("root", [
      { id: "cond-tenure", attribute: "tenureMonths", comparator: "in", value: ["13-24", "24+"] },
      { id: "cond-arpu", attribute: "arpuBand", comparator: "in", value: [">$75"] },
      { id: "cond-os", attribute: "deviceOS", comparator: "equals", value: "iOS" },
      { id: "cond-plan", attribute: "planType", comparator: "equals", value: "postpaid" },
      { id: "cond-lang", attribute: "language", comparator: "equals", value: "en" },
    ]),
    restrictedAttributes: ["bundleEligible"],
    metrics: {
      size: 18500,
      trend: 4.2,
      freshness: "2024-04-22T09:00:00Z",
      reach: {
        email: 16000,
        sms: 14200,
        whatsapp: 9200,
        retail: 8700,
        callCenter: 10300,
        paidSocial: 17600,
        display: 18800,
      },
      warnings: [],
      impact: {
        propensity: 0.22,
        conversions: 4070,
        revenue: 253000,
        paybackDays: 32,
        cost: 52000,
        margin: 201000,
      },
    },
    versions: [
      mkVersion(
        "seg-001-v1",
        "Initial launch cohort",
        "2024-03-12T10:00:00Z",
        mkGroup("root", [
          { id: "cond-tenure", attribute: "tenureMonths", comparator: "in", value: ["13-24", "24+"] },
          { id: "cond-arpu", attribute: "arpuBand", comparator: "in", value: [">$75"] },
          { id: "cond-plan", attribute: "planType", comparator: "equals", value: "postpaid" },
        ]),
        17100,
      ),
    ],
  },
  {
    id: "seg-002",
    name: "Prepaid price-sensitive savers",
    description: "Spanish-first prepaid residents balancing affordability programs and top-up cadence.",
    size: 26800,
    trend: -2.8,
    freshness: "2024-04-21T08:45:00Z",
    lastEdited: "2024-04-21T08:45:00Z",
    language: "es",
    rules: mkGroup("root", [
      { id: "cond-prepaid", attribute: "prepaid", comparator: "equals", value: true },
      { id: "cond-lang-es", attribute: "language", comparator: "equals", value: "es" },
      { id: "cond-arpu-mid", attribute: "arpuBand", comparator: "in", value: ["<$35", "$35-$55"] },
      { id: "cond-zone", attribute: "zone", comparator: "in", value: ["Carolina", "Caguas"] },
    ]),
    restrictedAttributes: ["planType"],
    metrics: {
      size: 26800,
      trend: -2.8,
      freshness: "2024-04-21T08:45:00Z",
      reach: {
        email: 18200,
        sms: 24000,
        whatsapp: 19500,
        retail: 13100,
        callCenter: 16500,
        paidSocial: 24100,
        display: 25600,
      },
      warnings: [
        {
          id: "email-threshold",
          channel: "Email",
          threshold: 2000,
          actual: 18200,
          severity: "warning",
          message: "Email universe meets guardrail; monitor deliverability cadence.",
        },
      ],
      impact: {
        propensity: 0.16,
        conversions: 4288,
        revenue: 147000,
        paybackDays: 41,
        cost: 61000,
        margin: 86000,
      },
    },
    versions: [
      mkVersion(
        "seg-002-v1",
        "Prepaid affordability baseline",
        "2024-02-18T09:30:00Z",
        mkGroup("root", [
          { id: "cond-prepaid", attribute: "prepaid", comparator: "equals", value: true },
          { id: "cond-lang-es", attribute: "language", comparator: "equals", value: "es" },
        ]),
        31200,
      ),
    ],
  },
  {
    id: "seg-003",
    name: "Fiber-pass mobile households",
    description: "Dual-service families in Liberty footprint with mobile single line ready for FWA upsell.",
    size: 14200,
    trend: 5.1,
    freshness: "2024-04-19T14:00:00Z",
    lastEdited: "2024-04-19T14:00:00Z",
    language: "es",
    rules: mkGroup("root", [
      { id: "cond-fiber", attribute: "hasFiberPass", comparator: "equals", value: true },
      { id: "cond-bundle", attribute: "bundleEligible", comparator: "equals", value: true },
      { id: "cond-plan-mobile", attribute: "planType", comparator: "equals", value: "postpaid" },
      { id: "cond-zone-south", attribute: "zone", comparator: "in", value: ["Ponce", "Mayagüez"] },
    ]),
    restrictedAttributes: ["tenureMonths"],
    metrics: {
      size: 14200,
      trend: 5.1,
      freshness: "2024-04-19T14:00:00Z",
      reach: {
        email: 12100,
        sms: 11800,
        whatsapp: 9700,
        retail: 8400,
        callCenter: 9300,
        paidSocial: 13400,
        display: 14600,
      },
      warnings: [],
      impact: {
        propensity: 0.19,
        conversions: 2698,
        revenue: 176000,
        paybackDays: 35,
        cost: 41000,
        margin: 135000,
      },
    },
    versions: [
      mkVersion(
        "seg-003-v1",
        "Initial fiber pass cohort",
        "2024-03-01T11:45:00Z",
        mkGroup("root", [
          { id: "cond-fiber", attribute: "hasFiberPass", comparator: "equals", value: true },
          { id: "cond-plan-mobile", attribute: "planType", comparator: "equals", value: "postpaid" },
        ]),
        13000,
      ),
    ],
  },
  {
    id: "seg-004",
    name: "Spanish-first Liberty Loop fans",
    description: "Families with Liberty Loop adoption momentum and WhatsApp consent across east zones.",
    size: 19800,
    trend: 6.4,
    freshness: "2024-04-18T07:30:00Z",
    lastEdited: "2024-04-18T07:30:00Z",
    language: "es",
    rules: mkGroup("root", [
      { id: "cond-language", attribute: "language", comparator: "equals", value: "es" },
      { id: "cond-bundle-yes", attribute: "bundleEligible", comparator: "equals", value: true },
      { id: "cond-consent", attribute: "consentWhatsApp", comparator: "equals", value: true },
      { id: "cond-zone-east", attribute: "zone", comparator: "in", value: ["Fajardo/Río Grande", "Caguas"] },
    ]),
    restrictedAttributes: ["planType"],
    metrics: {
      size: 19800,
      trend: 6.4,
      freshness: "2024-04-18T07:30:00Z",
      reach: {
        email: 15400,
        sms: 17600,
        whatsapp: 19800,
        retail: 9400,
        callCenter: 13200,
        paidSocial: 18200,
        display: 20800,
      },
      warnings: [
        {
          id: "display-threshold",
          channel: "Display",
          threshold: 10000,
          actual: 20800,
          severity: "warning",
          message: "Display universe cleared guardrail with strong headroom.",
        },
      ],
      impact: {
        propensity: 0.24,
        conversions: 4752,
        revenue: 228000,
        paybackDays: 29,
        cost: 68000,
        margin: 160000,
      },
    },
    versions: [
      mkVersion(
        "seg-004-v1",
        "Loop pilot",
        "2024-01-28T09:00:00Z",
        mkGroup("root", [
          { id: "cond-language", attribute: "language", comparator: "equals", value: "es" },
          { id: "cond-consent", attribute: "consentWhatsApp", comparator: "equals", value: true },
        ]),
        18000,
      ),
    ],
  },
];

export const segmentSampleProfiles: SegmentSampleProfile[] = [
  {
    id: "profile-001",
    name: "Camila – Promo seeker",
    attributes: {
      tenureMonths: "4-12",
      arpuBand: "$35-$55",
      deviceOS: "Android",
      hasFiberPass: false,
      prepaid: true,
      planType: "prepaid",
      bundleEligible: false,
      language: "es",
      consentSMS: true,
      consentWhatsApp: true,
      zone: "Carolina",
    },
    notes: "Relies on WhatsApp for promo alerts and reacts to loyalty streak offers.",
  },
  {
    id: "profile-002",
    name: "Luis – Loop enthusiast",
    attributes: {
      tenureMonths: "13-24",
      arpuBand: ">$75",
      deviceOS: "iOS",
      hasFiberPass: true,
      prepaid: false,
      planType: "bundle",
      bundleEligible: true,
      language: "es",
      consentSMS: true,
      consentWhatsApp: true,
      zone: "Caguas",
    },
    notes: "Champions Liberty Loop for extended family and open to device upgrades.",
  },
  {
    id: "profile-003",
    name: "Sofía – Hybrid worker",
    attributes: {
      tenureMonths: "24+",
      arpuBand: ">$75",
      deviceOS: "iOS",
      hasFiberPass: true,
      prepaid: false,
      planType: "postpaid",
      bundleEligible: true,
      language: "en",
      consentSMS: false,
      consentWhatsApp: false,
      zone: "San Juan Metro",
    },
    notes: "Needs symmetrical fiber reliability with managed security features.",
  },
  {
    id: "profile-004",
    name: "Jorge – Storm responder",
    attributes: {
      tenureMonths: "0-3",
      arpuBand: "<$35",
      deviceOS: "Android",
      hasFiberPass: false,
      prepaid: true,
      planType: "prepaid",
      bundleEligible: false,
      language: "es",
      consentSMS: true,
      consentWhatsApp: true,
      zone: "Mayagüez",
    },
    notes: "Activated during network events; expects real-time outage alerts.",
  },
];

export const campaignBriefs: CampaignBrief[] = [
  {
    id: "camp-001",
    name: "Liberty Loop loyalty boost",
    objective: "grow",
    status: "In Review",
    offerArchetype: "LibertyLoop",
    primaryKpi: "ARPU ↑",
    timeframe: "May 2024",
    linkedSegmentId: "seg-001",
    linkedOpportunityId: "opp-001",
    roiEstimate: 2.8,
    owner: "L. Martínez",
    createdAt: "2024-04-10T14:30:00Z",
    updatedAt: "2024-04-22T09:15:00Z",
    valuePropTemplate: "Liberty Loop bundle uplift",
    valueProp: "Bundle streaming credits with home + mobile convergence across east corridor households.",
    budget: 55000,
    dailyCap: 1800,
    eligibility: {
      prepaid: false,
      consentSMS: true,
      consentWhatsApp: true,
      bundleEligible: true,
      language: "es",
    },
    channelMix: [
      {
        channel: "Retail",
        focus: "San Juan Metro experience pod",
        rationale: "Foot traffic converts above 30% with Loop demos.",
      },
      {
        channel: "Call Center",
        focus: "Bundle concierge squad",
        rationale: "Handles billing migration for converged homes.",
      },
      {
        channel: "WhatsApp",
        focus: "Spanish-first concierge flows",
        rationale: "Preferred follow-up channel for metro households.",
      },
      {
        channel: "Email",
        focus: "Dynamic Loop personalization",
        rationale: "Drives cross-sell to high-ARPU profiles.",
      },
    ],
    assumptions: [
      "Field install partners maintain <5 day SLA for fiber upgrades.",
      "Bilingual assets receive approval 7 days before launch.",
      "Finance confirms Liberty Loop incentives weekly.",
    ],
    compliance: [
      "Validate WhatsApp opt-in status against consent lake.",
      "Retail signage must include Spanish disclaimers for bundles.",
    ],
    forecast: {
      reach: 18500,
      conversionRate: 0.18,
      conversions: 3330,
      cac: 16,
      roi: 2.8,
      revenue: 92400,
      spend: 33000,
    },
    versionHistory: [
      {
        id: "camp-001-v1",
        summary: "Initial Loop pilot draft",
        timestamp: "2024-03-28T12:10:00Z",
        author: "L. Martínez",
        status: "Draft",
        notes: "Seeded from Opportunity Radar context composer.",
      },
      {
        id: "camp-001-v2",
        summary: "Added WhatsApp concierge workflow",
        timestamp: "2024-04-18T15:40:00Z",
        author: "A. Rivera",
        status: "In Review",
        notes: "Aligned with Segment Studio guardrails.",
      },
    ],
    approvals: [
      {
        id: "camp-001-ap1",
        approver: "PMO – R. Santiago",
        status: "Pending",
        timestamp: "2024-04-22T09:10:00Z",
      },
      {
        id: "camp-001-ap2",
        approver: "Legal – E. Flores",
        status: "Approved",
        timestamp: "2024-04-19T13:20:00Z",
        comment: "Disclosures verified for Spanish copy.",
      },
    ],
    changeNotes: [
      "2024-04-22: Added bilingual signage requirement.",
      "2024-04-19: Updated ROI after refreshed segment size.",
    ],
  },
  {
    id: "camp-002",
    name: "Storm recovery makegood",
    objective: "retain",
    status: "Draft",
    offerArchetype: "OutageMakegood",
    primaryKpi: "Churn ↓",
    timeframe: "April–May 2024",
    linkedSegmentId: "seg-002",
    linkedOpportunityId: "opp-002",
    roiEstimate: 1.6,
    owner: "D. González",
    createdAt: "2024-04-05T10:45:00Z",
    updatedAt: "2024-04-21T16:05:00Z",
    valuePropTemplate: "Storm recovery credit",
    valueProp: "Automatic bill credits plus proactive outage alerts for prepaid Spanish-first subscribers.",
    budget: 28000,
    dailyCap: 900,
    eligibility: {
      prepaid: true,
      consentSMS: true,
      consentWhatsApp: true,
      bundleEligible: false,
      language: "es",
    },
    channelMix: [
      {
        channel: "Call Center",
        focus: "Specialized outage desk",
        rationale: "Resolves escalations and schedules credits in one call.",
      },
      {
        channel: "SMS",
        focus: "Credit confirmation + top-up reminder",
        rationale: "High open rate for prepaid segments.",
      },
      {
        channel: "WhatsApp",
        focus: "Two-way storm status updates",
        rationale: "Trusted format during recovery windows.",
      },
      {
        channel: "Retail",
        focus: "Pop-up assistance in Mayagüez",
        rationale: "Supports power restoration hot spots.",
      },
    ],
    assumptions: [
      "Credit ledger posts within 24 hours of storm flag.",
      "Network engineering shares outage map refresh twice daily.",
      "Retail micro-hubs staffed for extended hours post-storm.",
    ],
    compliance: [
      "Confirm TCPA language for SMS flows.",
      "Ensure Spanish push notifications mirror SMS copy.",
    ],
    forecast: {
      reach: 26800,
      conversionRate: 0.12,
      conversions: 3216,
      cac: 11,
      roi: 1.6,
      revenue: 48240,
      spend: 30150,
    },
    versionHistory: [
      {
        id: "camp-002-v1",
        summary: "Initial outage credit outline",
        timestamp: "2024-03-30T11:05:00Z",
        author: "D. González",
        status: "Draft",
        notes: "Baseline guardrails from Segment Studio applied.",
      },
      {
        id: "camp-002-v2",
        summary: "Layered WhatsApp automation",
        timestamp: "2024-04-21T15:45:00Z",
        author: "S. Méndez",
        status: "Draft",
        notes: "Awaiting compliance for opt-out phrasing.",
      },
    ],
    approvals: [
      {
        id: "camp-002-ap1",
        approver: "Operations – J. Morales",
        status: "Pending",
        timestamp: "2024-04-21T16:10:00Z",
        comment: "Need confirmation on crew capacity.",
      },
    ],
    changeNotes: [
      "2024-04-21: Added retail pop-up coverage for blackout zones.",
    ],
  },
  {
    id: "camp-003",
    name: "Liberty Loop SMB expansion",
    objective: "acquire",
    status: "Approved",
    offerArchetype: "BundleDiscount",
    primaryKpi: "CGA ↓",
    timeframe: "Q2 2024",
    linkedSegmentId: "seg-003",
    linkedOpportunityId: "opp-004",
    roiEstimate: 3.4,
    owner: "M. Vega",
    createdAt: "2024-03-15T09:25:00Z",
    updatedAt: "2024-04-20T08:55:00Z",
    valuePropTemplate: "SMB Liberty Loop",
    valueProp: "Converged connectivity, managed Wi-Fi, and POS prioritisation for retail SMB growth.",
    budget: 72000,
    dailyCap: 2100,
    eligibility: {
      prepaid: false,
      consentSMS: true,
      consentWhatsApp: true,
      bundleEligible: true,
      language: "es",
    },
    channelMix: [
      {
        channel: "Email",
        focus: "ROI calculator nurtures",
        rationale: "Educates SMB owners on total cost savings.",
      },
      {
        channel: "Retail",
        focus: "Bayamón Loop business bar",
        rationale: "Hosts live demos for SMB prospects.",
      },
      {
        channel: "Call Center",
        focus: "Dedicated SMB success pod",
        rationale: "Supports provisioning and credit checks.",
      },
      {
        channel: "WhatsApp",
        focus: "Spanish-first appointment scheduling",
        rationale: "Coordinates site surveys efficiently.",
      },
    ],
    assumptions: [
      "Provisioning team confirms same-week installs for SMB bundles.",
      "Billing system toggles Liberty Loop discounts automatically.",
      "SMB marketing kit localised for Spanish and English.",
    ],
    compliance: [
      "Verify opt-in for WhatsApp business messaging.",
      "Ensure financing terms disclosed in both languages.",
    ],
    forecast: {
      reach: 14200,
      conversionRate: 0.21,
      conversions: 2982,
      cac: 22,
      roi: 3.4,
      revenue: 154500,
      spend: 45500,
    },
    versionHistory: [
      {
        id: "camp-003-v1",
        summary: "SMB pilot concept",
        timestamp: "2024-03-15T09:25:00Z",
        author: "M. Vega",
        status: "Draft",
        notes: "Initial modelling sourced from Radar opportunity ranking.",
      },
      {
        id: "camp-003-v2",
        summary: "Approved with bundle financing",
        timestamp: "2024-04-20T08:55:00Z",
        author: "PMO",
        status: "Approved",
        notes: "Provisioning and billing validation complete.",
      },
    ],
    approvals: [
      {
        id: "camp-003-ap1",
        approver: "Finance – D. Torres",
        status: "Approved",
        timestamp: "2024-04-19T18:00:00Z",
        comment: "ROI validated against SMB baseline.",
      },
      {
        id: "camp-003-ap2",
        approver: "Compliance – I. Santiago",
        status: "Approved",
        timestamp: "2024-04-20T08:40:00Z",
      },
    ],
    changeNotes: [
      "2024-04-18: Added bilingual SMB marketing kit reference.",
      "2024-04-12: Increased daily cap based on segment readiness.",
    ],
  },
];

export const executionPipeline: ExecutionPipelineStage[] = [
  {
    id: "pipe-001",
    campaignId: "camp-001",
    name: "Planning",
    position: 0,
    progress: 100,
    owner: "L. Martínez",
    status: "on-track",
    updatedAt: "2024-04-19T08:15:00Z",
    notes: "Brief locked with Segment Studio references.",
  },
  {
    id: "pipe-002",
    campaignId: "camp-001",
    name: "Creative",
    position: 1,
    progress: 68,
    owner: "A. Rivera",
    status: "at-risk",
    updatedAt: "2024-04-22T07:45:00Z",
    notes: "Awaiting Spanish QA for WhatsApp flows.",
  },
  {
    id: "pipe-003",
    campaignId: "camp-001",
    name: "Targeting",
    position: 2,
    progress: 54,
    owner: "J. Morales",
    status: "on-track",
    updatedAt: "2024-04-21T16:30:00Z",
    notes: "Audience synced from Segment Studio seed.",
  },
  {
    id: "pipe-004",
    campaignId: "camp-001",
    name: "QA",
    position: 3,
    progress: 35,
    owner: "E. Flores",
    status: "on-track",
    updatedAt: "2024-04-22T11:10:00Z",
    notes: "Disclosure review scheduled.",
  },
  {
    id: "pipe-005",
    campaignId: "camp-001",
    name: "Launch",
    position: 4,
    progress: 0,
    owner: "PMO",
    status: "on-track",
    updatedAt: "2024-04-22T09:00:00Z",
    notes: "Pending creative QA sign-off.",
  },
  {
    id: "pipe-006",
    campaignId: "camp-001",
    name: "In-flight",
    position: 5,
    progress: 0,
    owner: "PMO",
    status: "on-track",
    updatedAt: "2024-04-22T09:00:00Z",
    notes: "Launch hand-off checklist drafted.",
  },
  {
    id: "pipe-007",
    campaignId: "camp-002",
    name: "Planning",
    position: 0,
    progress: 92,
    owner: "D. González",
    status: "on-track",
    updatedAt: "2024-04-21T15:30:00Z",
    notes: "Storm coverage modelling validated.",
  },
  {
    id: "pipe-008",
    campaignId: "camp-002",
    name: "Creative",
    position: 1,
    progress: 48,
    owner: "S. Méndez",
    status: "at-risk",
    updatedAt: "2024-04-21T16:00:00Z",
    notes: "Need bilingual push notification copy.",
  },
  {
    id: "pipe-009",
    campaignId: "camp-002",
    name: "Targeting",
    position: 2,
    progress: 61,
    owner: "J. Morales",
    status: "on-track",
    updatedAt: "2024-04-21T16:10:00Z",
    notes: "Consent filters verified for prepaid storm cohort.",
  },
  {
    id: "pipe-010",
    campaignId: "camp-002",
    name: "QA",
    position: 3,
    progress: 22,
    owner: "E. Flores",
    status: "at-risk",
    updatedAt: "2024-04-22T08:00:00Z",
    notes: "TCPA language pending final approval.",
  },
  {
    id: "pipe-011",
    campaignId: "camp-002",
    name: "Launch",
    position: 4,
    progress: 0,
    owner: "PMO",
    status: "on-track",
    updatedAt: "2024-04-21T12:00:00Z",
    notes: "Holding for QA clearance.",
  },
  {
    id: "pipe-012",
    campaignId: "camp-002",
    name: "In-flight",
    position: 5,
    progress: 0,
    owner: "PMO",
    status: "on-track",
    updatedAt: "2024-04-21T12:00:00Z",
    notes: "Readiness check incomplete.",
  },
  {
    id: "pipe-013",
    campaignId: "camp-003",
    name: "Planning",
    position: 0,
    progress: 100,
    owner: "M. Vega",
    status: "on-track",
    updatedAt: "2024-04-18T08:20:00Z",
    notes: "SMB focus alignment complete.",
  },
  {
    id: "pipe-014",
    campaignId: "camp-003",
    name: "Creative",
    position: 1,
    progress: 88,
    owner: "A. Rivera",
    status: "on-track",
    updatedAt: "2024-04-20T09:40:00Z",
    notes: "Bilingual asset toolkit approved.",
  },
  {
    id: "pipe-015",
    campaignId: "camp-003",
    name: "Targeting",
    position: 2,
    progress: 94,
    owner: "J. Morales",
    status: "on-track",
    updatedAt: "2024-04-19T17:05:00Z",
    notes: "Seeded from Segment Studio Liberty Loop SMB view.",
  },
  {
    id: "pipe-016",
    campaignId: "camp-003",
    name: "QA",
    position: 3,
    progress: 76,
    owner: "E. Flores",
    status: "on-track",
    updatedAt: "2024-04-20T08:30:00Z",
    notes: "Channel disclosures finalised.",
  },
  {
    id: "pipe-017",
    campaignId: "camp-003",
    name: "Launch",
    position: 4,
    progress: 42,
    owner: "PMO",
    status: "on-track",
    updatedAt: "2024-04-21T10:00:00Z",
    notes: "Provisioning flag validated.",
  },
  {
    id: "pipe-018",
    campaignId: "camp-003",
    name: "In-flight",
    position: 5,
    progress: 18,
    owner: "PMO",
    status: "on-track",
    updatedAt: "2024-04-21T10:00:00Z",
    notes: "Pilot stores prepping for go-live.",
  },
];

export const executionTasks: ExecutionTask[] = [
  {
    id: "task-001",
    campaignId: "camp-001",
    workstream: "Creative",
    owner: "A. Rivera",
    status: "In progress",
    dueDate: "2024-04-24",
    slaHours: 72,
    tags: ["Spanish QA", "Loop"],
    attachments: ["loop-creative-wireframes.pdf"],
    dependencies: ["task-006"],
    relatedOpportunityId: "opp-001",
    updatedAt: "2024-04-22T07:45:00Z",
    notes: "Awaiting localized hero copy approval.",
  },
  {
    id: "task-002",
    campaignId: "camp-001",
    workstream: "Data",
    owner: "J. Morales",
    status: "Not started",
    dueDate: "2024-04-25",
    slaHours: 48,
    tags: ["Audience", "URL-state"],
    attachments: ["loop-targeting-spec.xlsx"],
    dependencies: [],
    relatedOpportunityId: "opp-004",
    updatedAt: "2024-04-21T16:30:00Z",
    notes: "Need refreshed consent audit extract.",
  },
  {
    id: "task-003",
    campaignId: "camp-002",
    workstream: "Channels",
    owner: "K. Méndez",
    status: "Blocked",
    dueDate: "2024-04-23",
    slaHours: 36,
    tags: ["WhatsApp", "Storm"],
    attachments: ["storm-journey-flow.png"],
    dependencies: ["task-005"],
    relatedOpportunityId: "opp-002",
    updatedAt: "2024-04-21T18:20:00Z",
    notes: "Need compliance sign-off on opt-out language.",
  },
  {
    id: "task-004",
    campaignId: "camp-002",
    workstream: "Operations",
    owner: "R. Santiago",
    status: "In progress",
    dueDate: "2024-04-26",
    slaHours: 60,
    tags: ["Field", "Storm"],
    attachments: ["crew-readiness-checklist.docx"],
    dependencies: [],
    relatedOpportunityId: "opp-007",
    updatedAt: "2024-04-21T17:55:00Z",
    notes: "Coordinating generator deployment schedule.",
  },
  {
    id: "task-005",
    campaignId: "camp-002",
    workstream: "Legal",
    owner: "E. Flores",
    status: "In progress",
    dueDate: "2024-04-22",
    slaHours: 24,
    tags: ["Compliance", "TCPA"],
    attachments: ["sms-disclosure-draft.docx"],
    dependencies: [],
    updatedAt: "2024-04-22T08:00:00Z",
    notes: "Reviewing bilingual SMS disclosures.",
  },
  {
    id: "task-006",
    campaignId: "camp-001",
    workstream: "Finance",
    owner: "D. González",
    status: "Done",
    dueDate: "2024-04-18",
    slaHours: 24,
    tags: ["Budget"],
    attachments: ["loop-budget-approval.pdf"],
    dependencies: [],
    updatedAt: "2024-04-19T10:05:00Z",
    notes: "Budget uplift approved.",
  },
  {
    id: "task-007",
    campaignId: "camp-003",
    workstream: "Field",
    owner: "M. Torres",
    status: "Not started",
    dueDate: "2024-04-29",
    slaHours: 72,
    tags: ["Provisioning", "SMB"],
    attachments: ["smb-site-survey-template.docx"],
    dependencies: ["task-008"],
    relatedOpportunityId: "opp-003",
    updatedAt: "2024-04-20T12:30:00Z",
    notes: "Waiting on appointment scheduling automation.",
  },
  {
    id: "task-008",
    campaignId: "camp-003",
    workstream: "CX",
    owner: "S. Méndez",
    status: "In progress",
    dueDate: "2024-04-21",
    slaHours: 36,
    tags: ["SMB", "Spanish copy"],
    attachments: ["smb-onboarding-script.pdf"],
    dependencies: [],
    relatedOpportunityId: "opp-006",
    updatedAt: "2024-04-20T10:05:00Z",
    notes: "Finalizing bilingual onboarding flow.",
  },
  {
    id: "task-009",
    campaignId: "camp-003",
    workstream: "Automation",
    owner: "C. Vega",
    status: "Not started",
    dueDate: "2024-04-28",
    slaHours: 48,
    tags: ["Journey", "SMB"],
    attachments: ["loop-automation-plan.json"],
    dependencies: ["task-002"],
    relatedOpportunityId: "opp-003",
    updatedAt: "2024-04-19T18:10:00Z",
    notes: "Awaiting targeting attributes from Segment Studio.",
  },
  {
    id: "task-010",
    campaignId: "camp-001",
    workstream: "Insights",
    owner: "B. López",
    status: "In progress",
    dueDate: "2024-04-22",
    slaHours: 24,
    tags: ["Forecast"],
    attachments: ["loop-measurement-plan.pptx"],
    dependencies: [],
    updatedAt: "2024-04-21T14:20:00Z",
    notes: "Aligning KPIs with Monitoring dashboard.",
  },
];

export const executionRisks: ExecutionRisk[] = [
  {
    id: "risk-001",
    severity: "High",
    owner: "PMO",
    description: "Hurricane season freeze window overlaps with planned Loop launch dates.",
    mitigation: "Pre-build pause messaging and secure flexible launch windows.",
    status: "Open",
    tags: ["Hurricane season freeze windows", "Scheduling"],
  },
  {
    id: "risk-002",
    severity: "Medium",
    owner: "Field Ops",
    description: "Power outage communications may delay in-store demos in Mayagüez.",
    mitigation: "Deploy battery backups and SMS alerts for store teams.",
    status: "Open",
    tags: ["power outage communications", "Storm"],
  },
  {
    id: "risk-003",
    severity: "Medium",
    owner: "Creative",
    description: "Bilingual asset readiness pending final QA.",
    mitigation: "Schedule dedicated QA slot and add backup translator.",
    status: "Mitigated",
    tags: ["bilingual asset readiness", "Compliance"],
  },
];

export const monitoringKpis: MonitoringKPI[] = [
  {
    id: "kpi-activations",
    label: "Activations",
    actual: 1480,
    plan: 1320,
    previous: 1180,
    unit: "count",
    trend: 9.8,
    confidence: "High",
  },
  {
    id: "kpi-churn",
    label: "Churn",
    actual: 2.6,
    plan: 3.1,
    previous: 3.4,
    unit: "percent",
    trend: -0.8,
    confidence: "Medium",
  },
  {
    id: "kpi-cac",
    label: "CAC",
    actual: 54,
    plan: 58,
    previous: 61,
    unit: "currency",
    trend: -1.2,
    confidence: "Medium",
  },
  {
    id: "kpi-arpu",
    label: "ARPU",
    actual: 74,
    plan: 70,
    previous: 69,
    unit: "currency",
    trend: 1.5,
    confidence: "High",
  },
  {
    id: "kpi-revenue",
    label: "Revenue",
    actual: 328000,
    plan: 310000,
    previous: 295000,
    unit: "currency",
    trend: 4.7,
    confidence: "High",
  },
];

export const monitoringSeries: MonitoringSeries[] = [
  {
    id: "series-activations",
    name: "Activations",
    metric: "Activations",
    points: Array.from({ length: 10 }).map((_, idx) => ({
      date: `2024-0${Math.floor(idx / 3) + 1}-${(idx % 10) + 1}`,
      actual: 900 + idx * 65,
      plan: 880 + idx * 55,
      previous: 820 + idx * 50,
    })),
  },
  {
    id: "series-churn",
    name: "Churn",
    metric: "Churn",
    points: Array.from({ length: 10 }).map((_, idx) => ({
      date: `2024-0${Math.floor(idx / 3) + 1}-${(idx % 10) + 1}`,
      actual: Number((3.8 - idx * 0.15).toFixed(2)),
      plan: Number((4.0 - idx * 0.12).toFixed(2)),
      previous: Number((4.2 - idx * 0.1).toFixed(2)),
    })),
  },
  {
    id: "series-revenue",
    name: "Revenue",
    metric: "Revenue",
    points: Array.from({ length: 10 }).map((_, idx) => ({
      date: `2024-0${Math.floor(idx / 3) + 1}-${(idx % 10) + 1}`,
      actual: 240000 + idx * 9500,
      plan: 230000 + idx * 8800,
      previous: 220000 + idx * 8200,
    })),
  },
];

export const monitoringBreakdowns: MonitoringBreakdown[] = [
  {
    id: "breakdown-channel",
    label: "Channel mix",
    type: "channel",
    slices: [
      { key: "Retail", actual: 32, plan: 28 },
      { key: "Call Center", actual: 24, plan: 22 },
      { key: "SMS", actual: 18, plan: 20 },
      { key: "WhatsApp", actual: 16, plan: 15 },
      { key: "Email", actual: 10, plan: 15 },
    ],
  },
  {
    id: "breakdown-segment",
    label: "Segment contribution",
    type: "segment",
    slices: [
      { key: "seg-001", actual: 38 },
      { key: "seg-002", actual: 29 },
      { key: "seg-003", actual: 21 },
      { key: "seg-004", actual: 12 },
    ],
  },
  {
    id: "breakdown-offer",
    label: "Offer archetype",
    type: "offer",
    slices: [
      { key: "LibertyLoop", actual: 36 },
      { key: "OutageMakegood", actual: 24 },
      { key: "BundleDiscount", actual: 28 },
      { key: "RetentionCredit", actual: 12 },
    ],
  },
];

export const monitoringFunnel: MonitoringFunnelStep[] = [
  { label: "Impressions", count: 128000 },
  { label: "Clicks", count: 28600, previous: 24400 },
  { label: "Engaged", count: 16800, previous: 14000 },
  { label: "Activations", count: 1480, previous: 1180 },
];

export const monitoringAlerts: MonitoringAlert[] = [
  {
    id: "alert-001",
    message: "WhatsApp engagement dipped below alert threshold in Mayagüez.",
    severity: "warning",
    createdAt: "2024-04-21T10:20:00Z",
    metric: "WhatsApp engagement",
    threshold: 18,
    actual: 15,
  },
  {
    id: "alert-002",
    message: "CAC trending 5% higher than plan for SMB offers.",
    severity: "info",
    createdAt: "2024-04-22T08:00:00Z",
    metric: "CAC",
    threshold: 52,
    actual: 54,
  },
];

export const defaultMonitoringViews: MonitoringSavedView[] = [
  {
    id: "view-loop-weekly",
    name: "Liberty Loop weekly",
    createdAt: "2024-04-01T08:00:00Z",
    updatedAt: "2024-04-22T09:00:00Z",
    filters: {
      channels: ["Retail", "WhatsApp"],
      segments: ["seg-001", "seg-004"],
      offers: ["LibertyLoop", "BundleDiscount"],
      dateRange: {
        from: "2024-04-01",
        to: "2024-04-22",
      },
      alertThreshold: 18,
    },
  },
  {
    id: "view-storm-readout",
    name: "Storm recovery",
    createdAt: "2024-04-15T08:00:00Z",
    updatedAt: "2024-04-21T15:30:00Z",
    filters: {
      channels: ["SMS", "WhatsApp", "Call Center"],
      segments: ["seg-002"],
      offers: ["OutageMakegood", "RetentionCredit"],
      dateRange: {
        from: "2024-04-10",
        to: "2024-04-22",
      },
      alertThreshold: 16,
    },
  },
];

export const kpiBundles: KPIBundle[] = [
  {
    id: "kpi-activations",
    name: "Activations vs plan",
    metric: "Activations",
    series: monitoringSeries[0].points.map((point) => ({
      date: point.date,
      value: point.actual,
    })),
  },
  {
    id: "kpi-revenue",
    name: "Revenue growth",
    metric: "Revenue",
    series: monitoringSeries[2].points.map((point) => ({
      date: point.date,
      value: point.actual,
    })),
  },
];
